name: Java CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Display GitHub Workspace
        run: echo "GitHub Workspace ${GITHUB_WORKSPACE}"
        
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          nmae: jar-file
          path: $GITHUB_WORKSPACE/target/appium_flutterfinder_java-1.0.5.jar
